'use client';

import { Canvas, useFrame } from '@react-three/fiber';
import { Html, RoundedBox, Sparkles, MeshDistortMaterial, Float } from '@react-three/drei';
import { Suspense, useEffect, useRef } from 'react';
import * as THREE from 'three';

function InvoiceCard({ pointerRef, scrollRef }) {
  const group = useRef();

  useFrame((state, delta) => {
    if (!group.current) return;
    // gentle continuous autorotation
    group.current.rotation.y += delta * 0.12;
    // scroll adds extra spin so the camera feels like it's orbiting as you scroll
    group.current.rotation.y += scrollRef.current * 0.0006;

    // mouse-driven natural tilt
    const targetX = pointerRef.current.y * 0.28;
    const targetZ = -pointerRef.current.x * 0.16;
    group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, targetX, 0.06);
    group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, targetZ, 0.06);
  });

  return (
    <Float speed={1.4} rotationIntensity={0.15} floatIntensity={0.6}>
      <group ref={group}>
        <RoundedBox args={[2.7, 3.7, 0.09]} radius={0.14} smoothness={4}>
          <meshPhysicalMaterial
            color="#171334"
            transparent
            opacity={0.5}
            roughness={0.12}
            metalness={0.25}
            transmission={0.55}
            thickness={0.6}
            clearcoat={1}
            clearcoatRoughness={0.1}
            emissive="#6D5EF0"
            emissiveIntensity={0.12}
          />
        </RoundedBox>

        {/* glowing edge outline */}
        <lineSegments>
          <edgesGeometry args={[new THREE.BoxGeometry(2.7, 3.7, 0.09)]} />
          <lineBasicMaterial color="#A78BFA" transparent opacity={0.55} />
        </lineSegments>

        <Html
          transform
          occlude
          distanceFactor={2.35}
          position={[0, 0, 0.06]}
          style={{ pointerEvents: 'none' }}
        >
          <div className="w-[260px] rounded-2xl px-5 py-5 select-none">
            <div className="font-display text-lg text-violet-100 tracking-wide">INVOICE</div>
            <div className="font-mono text-[10px] text-violet-300/50 mb-4">#INV-2026-0417</div>
            <div className="space-y-2 text-[11px] text-violet-100/70 font-sans">
              <div className="flex justify-between border-b border-white/10 pb-1.5">
                <span>Consulting services</span><span className="font-mono">Rs. 18,000</span>
              </div>
              <div className="flex justify-between border-b border-white/10 pb-1.5">
                <span>Design assets</span><span className="font-mono">Rs. 9,500</span>
              </div>
              <div className="flex justify-between border-b border-white/10 pb-1.5">
                <span>Software license</span><span className="font-mono">Rs. 15,000</span>
              </div>
            </div>
            <div className="mt-4 flex items-baseline justify-between">
              <span className="text-[9px] uppercase tracking-[0.18em] text-violet-300/45">Total due</span>
              <span className="font-mono text-lg text-white">Rs. 42,500</span>
            </div>
            <div className="mt-3 inline-flex items-center gap-1.5 text-[9px] text-emerald-300/80">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse-glow" />
              Generated by AI in 4s
            </div>
          </div>
        </Html>
      </group>
    </Float>
  );
}

function AIOrb({ pointerRef }) {
  const ref = useRef();
  useFrame((state) => {
    if (!ref.current) return;
    ref.current.rotation.y += 0.006;
    ref.current.position.y = 0.4 + Math.sin(state.clock.elapsedTime * 0.9) * 0.18;
    ref.current.position.x = 2.25 + pointerRef.current.x * 0.12;
  });

  return (
    <group ref={ref} position={[2.25, 0.4, 0.2]}>
      <mesh>
        <sphereGeometry args={[0.4, 64, 64]} />
        <MeshDistortMaterial
          color="#8B5CF6"
          emissive="#8B5CF6"
          emissiveIntensity={1.1}
          distort={0.32}
          speed={1.8}
          roughness={0.15}
          metalness={0.5}
        />
      </mesh>
      <pointLight color="#8B5CF6" intensity={3.5} distance={4} />
    </group>
  );
}

function Lights() {
  return (
    <>
      <ambientLight intensity={0.35} />
      <directionalLight position={[4, 5, 3]} intensity={0.9} color="#C4B5FD" />
      <directionalLight position={[-4, -2, -3]} intensity={0.4} color="#60A5FA" />
      <pointLight position={[0, 0, 3]} intensity={0.6} color="#A78BFA" />
    </>
  );
}

export default function Hero3D() {
  const pointerRef = useRef({ x: 0, y: 0 });
  const scrollRef = useRef(0);

  useEffect(() => {
    function handlePointerMove(e) {
      pointerRef.current = {
        x: (e.clientX / window.innerWidth) * 2 - 1,
        y: (e.clientY / window.innerHeight) * 2 - 1,
      };
    }
    function handleScroll() {
      scrollRef.current = window.scrollY;
    }
    window.addEventListener('pointermove', handlePointerMove);
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => {
      window.removeEventListener('pointermove', handlePointerMove);
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <Canvas
      camera={{ position: [0, 0, 7.2], fov: 42 }}
      dpr={[1, 1.75]}
      gl={{ antialias: true, alpha: true }}
    >
      <Suspense fallback={null}>
        <Lights />
        <Sparkles count={90} scale={[8, 6, 4]} size={2.2} speed={0.25} color="#A78BFA" opacity={0.6} />
        <Sparkles count={40} scale={[9, 7, 5]} size={1.4} speed={0.15} color="#60A5FA" opacity={0.4} />
        <InvoiceCard pointerRef={pointerRef} scrollRef={scrollRef} />
        <AIOrb pointerRef={pointerRef} />
      </Suspense>
    </Canvas>
  );
}
